# Generated by Django 2.2 on 2019-04-04 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Peg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('color', models.IntegerField(choices=[(0, 'WHITE'), (1, 'YELLOW'), (2, 'ORANGE'), (3, 'RED'), (4, 'GREEN'), (5, 'BLUE'), (6, 'BROWN'), (7, 'BLACK')])),
            ],
        ),
        migrations.CreateModel(
            name='Guess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('correct_positions', models.IntegerField(default=0)),
                ('correct_colors', models.IntegerField(default=0)),
                ('code_guess', models.ManyToManyField(to='game.Peg')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret_code', models.ManyToManyField(to='game.Peg')),
            ],
        ),
    ]
