# Generated by Django 2.2 on 2019-04-05 21:52

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import game.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret_code', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('WHITE', 'WHITE'), ('YELLOW', 'YELLOW'), ('ORANGE', 'ORANGE'), ('RED', 'RED'), ('GREEN', 'GREEN'), ('BLUE', 'BLUE'), ('BROWN', 'BROWN'), ('BLACK', 'BLACK')], max_length=10), default=game.models.create_secret_code, editable=False, size=4)),
            ],
        ),
        migrations.CreateModel(
            name='Guess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('code_guess', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('WHITE', 'WHITE'), ('YELLOW', 'YELLOW'), ('ORANGE', 'ORANGE'), ('RED', 'RED'), ('GREEN', 'GREEN'), ('BLUE', 'BLUE'), ('BROWN', 'BROWN'), ('BLACK', 'BLACK')], max_length=10), editable=False, size=4)),
                ('correct_positions', models.IntegerField(default=0)),
                ('correct_colors', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Game')),
            ],
            options={
                'ordering': ['game', 'create_date'],
            },
        ),
    ]
