# Generated by Django 2.2 on 2019-04-05 21:52

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import game.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret_code', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(choices=[(0, 'WHITE'), (1, 'YELLOW'), (2, 'ORANGE'), (3, 'RED'), (4, 'GREEN'), (5, 'BLUE'), (6, 'BROWN'), (7, 'BLACK')]), default=game.models.create_secret_code, editable=False, size=4)),
            ],
        ),
        migrations.CreateModel(
            name='Guess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('code_guess', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(choices=[(0, 'WHITE'), (1, 'YELLOW'), (2, 'ORANGE'), (3, 'RED'), (4, 'GREEN'), (5, 'BLUE'), (6, 'BROWN'), (7, 'BLACK')]), editable=False, size=4), size=None)),
                ('correct_positions', models.IntegerField(default=0)),
                ('correct_colors', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Game')),
            ],
            options={
                'ordering': ['game', 'create_date'],
            },
        ),
    ]
