# Generated by Django 2.2 on 2019-04-06 19:08

import django.contrib.postgres.fields
from django.db import migrations, models
import game.models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='secret_code',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('WHITE', 'WHITE'), ('YELLOW', 'YELLOW'), ('ORANGE', 'ORANGE'), ('RED', 'RED'), ('GREEN', 'GREEN'), ('BLUE', 'BLUE'), ('BROWN', 'BROWN'), ('BLACK', 'BLACK')], max_length=10), default=game.models.create_secret_code, editable=False, size=4),
        ),
        migrations.AlterField(
            model_name='guess',
            name='code_guess',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('WHITE', 'WHITE'), ('YELLOW', 'YELLOW'), ('ORANGE', 'ORANGE'), ('RED', 'RED'), ('GREEN', 'GREEN'), ('BLUE', 'BLUE'), ('BROWN', 'BROWN'), ('BLACK', 'BLACK')], max_length=10), editable=False, size=4), size=None),
        ),
    ]
