# Generated by Django 4.2.17 on 2025-01-02 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20190406_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guess',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guesses', to='game.game'),
        ),
    ]
