# Generated by Django 4.2.17 on 2025-01-02 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_alter_guess_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_won',
            field=models.BooleanField(default=False),
        ),
    ]
